### PR TITLE
Feature new desing ereferrals

### LINKED ISSUE #1360: Final design review
Using this [mockup](http://web2.beckolsystem.com/connect/#/screens/d12245cc-1680-458d-89dd-4f0d7fb22724), a general design review is needed

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Close #1360

### CODE REVIEW

**Comment by manuelplazaspalacio** [comment]
Changes done @xurxodev

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio I have requested some changes on this PR:
- Icon in header is distinct
- Icons of tabs is fuzzy
## Survey
- Top texts are distinct than design (New Survey, text according to program (Uganda...)
## Av Library
- In design, the no selected option (Grid, List) has icon color distinct than selected, in Android app are equals
- Items for grid and list mode is not equal to design

**Comment by manuelplazaspalacio** [comment]
Solved bugs @xurxodev  except :
Av Library
In design, the no selected option (Grid, List) has icon color distinct than selected, in Android app are equals.
They only provide to us an icon and a color.

**Review by xurxodev — APPROVED** [review]
thanks @manuelplazaspalacio

**Pull request merged**
