### PR TITLE
Bug infinite login on invalid pin

### LINKED ISSUE #1444: On password change, if password's introduced wrong push fails
- Progress bar continues "ad eternum"

### LINKED ISSUE #1445: Push not working after pass changed

### LINKED ISSUE #1483: On password change and password entered wrong, vouchers are sent
- Vouchers in queue are sent (even without authorisation)

### PR DESCRIPTION
**Pull request by idelcano**
Closes #1444 
Closes #1445 
Closes #1483

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@idelcano If you change the password, introduce bad credentials and then good credentials, it seems that the push alarm is not reactivated. Can you change that? thanks!

**Comment by idelcano** [comment]
@ifoche Done. 
This PR closes 3  issues: 
Closes #1444
Closes #1445
Closes #1483

**Review by ifoche — APPROVED** [review]
thanks @idelcano

**Review by ifoche — CHANGES_REQUESTED** [review]
@idelcano I don't get the point on adding an invalid attempt onPinChanged(). That's causing the login to be blocked even without introducing the password wrong. Can you change that please? Thanks!

**Review by ifoche — APPROVED** [review]
thanks @idelcano

**Pull request merged**
