### PR TITLE
Feature np mz csvs

### LINKED ISSUE #1432: Add MZ and NP languages, programs and options

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Close #1432

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio with this code when I am going to create a new survey, questions do not appear and progress bar is always visible

**Comment by manuelplazaspalacio** [comment]
Solved bug @xurxodev

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio mozambique and nepali does not appear in language option on settings activity and the flag is not shown under resource directory. I think that mz y np are not valid locale codes

**Comment by manuelplazaspalacio** [comment]
@xurxodev .Solve bug with incorrect locale, but in settings not apear to select the lenguage, loock like a problem in the get AppLanguages in the settings activity

**Comment by xurxodev** [comment]
@manuelplazaspalacio For me an issue to add a new language finish when I can select this new language in the app, please review settings activity and fix languages view to show all languages if It's necessary

**Comment by manuelplazaspalacio** [comment]
@xurxodev  solved bug

**Comment by ifoche** [comment]
@manuelplazaspalacio moving back this issue to ready because we've just received the users and codes to test Nepal and Mozambique. They're these:
1) Test OUs
For Nepal: https://data.psi-mis.org/api/25/organisationUnits/hRfSrIPvgLt.json
For Mozambique: https://data.psi-mis.org/api/25/organisationUnits/ZUF1vSkQaB0.json
(They will be available in clone from tomorrow)

2) Missing codes. Waiting for confirmation, but it seems that the codes are these ones (strange that they have spaces...):
"Source of information"
"Is client referred?"
"Service date"
"Service desired"
"Health facility code"
"Household delivery"
"Address"
"Phone contact consent"

**Comment by ifoche** [comment]
@manuelplazaspalacio forget about the missing codes I wrote you in my previous comment. They just sent me new config files for all TZ, MZ and NP with the codes. Hopefully only those codes changes, but please re-check all. I just shared with you

**Comment by manuelplazaspalacio** [comment]
Put correct csvs

**Review by ifoche — CHANGES_REQUESTED** [review]
Can you review it again @manuelplazaspalacio? I've only checked Tanzania, but I can see at least the following problems (for reference, please look at [this file](https://drive.google.com/drive/u/1/folders/0B7TXlu17DcAbZjBLZGFfSHQ0SHc)):
- Question order is different (i.e program is not the first question, civil status is not under year of birth...)
- Number of living children appears as # Children 
Thanks!

**Comment by manuelplazaspalacio** [comment]
Solved bugs

**Review by ifoche — APPROVED** [review]
thanks @manuelplazaspalacio

**Pull request merged**
