### PR TITLE
Feature login types soft and full

### LINKED ISSUE #1655: Login improvements

### PR DESCRIPTION
**Pull request by Amejia481**
close #1655 
#  Full-login
## Demo Video
https://drive.google.com/file/d/1XL1shtYtggS5df5_wNy6h6o7JL7SIZoR/view?usp=sharing

### Without Clicking "Advanced Options" 
image

### Without Clicking "Advanced Options"
image

# Soft-login
## Demo video.
https://drive.google.com/open?id=1vcjSlkZYifg4FRfnrt4ATdozLb2UfbpM

### Without Clicking "Advanced Options" 

image

### Without Clicking "Advanced Options" 
image

### CODE REVIEW

**Comment by Amejia481** [comment]
close #1723

**Review by ifoche — CHANGES_REQUESTED** [review]
@Amejia481 a couple of functional changes: 
1) When "Advanced Options" is deployed, the text should say "Simple Options", and back again to "Advance Options" when deployed again.
2) On a full login, demo button appears on top, but should appear under login, just like log out button on sof login.

Can you please take care of it? Thanks!

**Comment by Amejia481** [comment]
Sure!

**Comment by Amejia481** [comment]
Hi @ifoche, 
I updated the PR, with the new changes.

**Review by ifoche — APPROVED** [review]
thanks @Amejia481

**Pull request merged**
