### PR TITLE
Feature allow 0 age add months age #2043

### LINKED ISSUE #2043: For both VMW and HC, allow 0 for age, and when 0 is added ask for months
This would imply creating a a parent-child hide logic and send the months against a separate DE. By now we still don't have the new DE for months, but it will be created soon and updated in this waffle issue

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Close #2043

### CODE REVIEW

**Comment by manuelplazaspalacio** [comment]
I didn't do migration because @idelcano  is doing it in issue #2044

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio There are somethings to review:
- I have doubts resolving the conflicts to merge with development, can you merging with development and resolve conflicts?
- create unit tests for new value object AgeMonthNumber 
- create db migration as @idelcano in https://github.com/EyeSeeTea/pictureapp/pull/2049
- avoid duplicate code in next methods on NavigationController

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio this issue works for HC but for VL org units and VMW program does not work, can you review it? thanks

**Comment by xurxodev** [comment]
please merge on this branch development previously because there is conflicts

**Review by xurxodev — APPROVED** [review]
thanks @manuelplazaspalacio

**Pull request merged**
