### PR TITLE
Feature implement treatement matrix db

### LINKED ISSUE #685: Implement Treatment Matrix DB
- [x] Implement pojos
- [x] Create Migration for Laos & Cambodia

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Close #685

### CODE REVIEW

**Comment by ifoche** [comment]
Pending tasks: 
- [ ] Re-do PR against development

**Comment by manuelplazaspalacio** [comment]
Con @ifoche

**Comment by manuelplazaspalacio** [comment]
@ifoche pr ready

**Comment by manuelplazaspalacio** [comment]
@ifoche pr ready

**Pull request merged**
