### PR TITLE
Adding ou and program to action bar

### LINKED ISSUE #1909: actionbar should show selected OU and program

### PR DESCRIPTION
**Pull request by Amejia481**
close #1909

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@Amejia481 we have to add two concepts to toolbar:
- The selected org unit and this is ok
- The selected program, we should add the program code also to the toolbar, for example:
Org unit name - program code

**Comment by Amejia481** [comment]
Hi @xurxodev, 

**The orgUnit name is too big to fit on the same line with the program, as you can see in the image below:**

image

**Can I add it in two lines, OrgUnit name on the first line and the second the program?**

image

**Comment by xurxodev** [comment]
@Amejia481 d7iipQZaHad is not the code for the program, It's a uid, the code is HC that It's smaller, we should not remove app name. I think is better set a smaller font to orgunit name - program code if is necessary.

**Comment by Amejia481** [comment]
Got it!

**Comment by Amejia481** [comment]
Thanks @xurxodev, now it fits:

image

**Comment by Amejia481** [comment]
@xurxodev it's done!

**Review by xurxodev — APPROVED** [review]
thanks @Amejia481. I have refactored your code a little to use baseActivityStrategy because this customization on the toolbar (org unit - program) is only for CNM

**Comment by Amejia481** [comment]
Thanks @xurxodev !

**Pull request merged**
