### PR TITLE
Maintenance add vmw program

### LINKED ISSUE #1849: Add VMW program
See the DEs explanation [here](https://drive.google.com/open?id=1SYXxmEw_9UITb_gODTUmka9luiqRohSXcMHAdt0eCiE)

This task implies the CSVs modification to add the program. To check it I would recommend to temporary point the logged user to this program and check if everything looks properly. Please drop some comments describing how to test it for the reviewer when its developed.

### PR DESCRIPTION
**Pull request by Amejia481**
close #1849

### CODE REVIEW

**Comment by Amejia481** [comment]
To test it, you have to change the actual program to the new one MVW, please follow these steps:

Change the `/pictureapp/app/src/cnm/res/values/donottranslate.xml`
On line 44 

Replace:
```xml
 <string name="malaria_program_uid" translatable="false">d7iipQZaHad</string>
```
By:
```xml
 <string name="malaria_program_uid" translatable="false">BSLefu6qGzn</string>
```
On Line 82
/pictureapp/app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/NavigationBuilder.java

 
Replace   
```java
  final QuestionDB rootQuestionDB = QuestionDB.findRootQuestion(tabDB);
```
By:
```java
final QuestionDB rootQuestionDB = QuestionDB.findRootQuestion(TabDB.findById(5l));
```

**Comment by Amejia481** [comment]
@ifoche 
There are some images that are pending from the designer:

- Pending images (Mobile,Non-mobile) MCS - Patient status cl5cDW7AxAj
- Pending images (Complete,Non-complete) MCS - DOT ax04nLeSaXw

Also, all the questions text are white color, they were this way on the last merged pull request #1863, from where I created this branch from, I not quite sure if it is modified on another pull request or should I updated it? 

screenshot_1520865956
screenshot_1520865976

**Review by ifoche — CHANGES_REQUESTED** [review]
@Amejia481 some changes here, that I'm asking @manuelplazaspalacio to implement given that it's not a good timing for you.

1. If you enter with a normal HC user, there's an extra not tested option...
screenshot_20180313-093554

2. Same thing for the treatment question...
screenshot_20180313-093720

3. The HC/VMW program selector (by OUGroup) seems to be failing. Instead of doing what you said in this PR, I setup an OU belonging to VMW OU Group, and looking at the preferences, the OUGroup code is properly set (k3HHkiUDu1K) but the OUGroup ID says HC. As a result, it's not understanding that program to be used is VMW one and therefore, it's opening the HC program even if we select a VMW village.

4.After doing the changes you suggested to access VMW program mocking the automatic program selection, then I get the following problems:

4.1. Question title for test result shows the key and not the title
screenshot_20180313-094540

4.2. For patient status, it's true that we don't have yet the images, but the text for the options is showing the string key
screenshot_20180313-094716

@manuelplazaspalacio can you please have a look and try to solve it? @Amejia481 can you please help @manuelplazaspalacio whenever you're available?

Thank you both

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio  I have found some problems:
- When I create a new survey for program vmw, after sending in review screen this survey is not on any list
- First question options should be rdt result images and not microscope result images
Can you review it? thanks

**Comment by manuelplazaspalacio** [comment]
When I create a new survey for program vmw, after sending in review screen this survey is not on any list
Solved in issue #1887

**Review by ifoche — APPROVED** [review]
thanks @Amejia481, @manuelplazaspalacio & @xurxodev

**Pull request merged**
