### PR TITLE
Add ProgramProgramRelation table

### LINKED ISSUE #1848: Add ProgramProgramRelation table
- [x] Add ProgramProgramRelation model
- [x] Add DB migrations if needed

### PR DESCRIPTION
**Pull request by Amejia481**
close #1848

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@Amejia481 there is a problem on this branch if you have a development installation (database version 13) and executes this (changing database version to 14). I think the problem is that a database migration is necessary. Can you review it, please?

**Comment by Amejia481** [comment]
Sure!

**Comment by Amejia481** [comment]
I did as you suggested.

1. I installed the app with the development installation 
(**database version 13 and app versionCode 51**)
2. I installed the app with this branch version installation 
(**database version 14 and app versionCode 42**)

The only issue that I had was with **the app versionCode 42**, that was bigger on the development installation and the app complained because It was downgrading the app **versionCode from 51 to versionCode 42.**

For this reason, I increased the **database version to 14 and the app versionCode to 52**, to avoid this issue. I think we do not need a database migration, **because I'm just adding a new table no altering any existing extructure.**

**Note:** I changed the base branch from `feature-expense_stock_normal_survey`  to `development`, because I believe that I really need anything from `feature-expense_stock_normal_survey` brach to add the new table.

If is there anything that is not clear, please let me know!

**Review by xurxodev — APPROVED** [review]
thanks @Amejia481. Increase versionCode to 52 is not necessary because development is 51

**Pull request merged**
