### PR TITLE
Feature new format push

### LINKED ISSUE #1382: Change request to new format

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Close #1382

### CODE REVIEW

**Comment by manuelplazaspalacio** [comment]
Push working @xurxodev

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio When I do login with manu 0000 an invalid credentials message is shown in screen

**Comment by manuelplazaspalacio** [comment]
@xurxodev  use users 8002 or 8001. Manu is not in the new server.

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio the push process is failing by timeout when I create one survey, can you review it please?

**Comment by manuelplazaspalacio** [comment]
Solved bug with timeout @xurxodev

**Review by xurxodev — APPROVED** [review]
thanks @manuelplazaspalacio

**Pull request merged**
