### PR TITLE
Fix server settings bug

### LINKED ISSUE #2278: Fix Login process from settings
Require #2250 because is where the bug is introduced:
 - [ ] ServerURL is showed only when developer options preference is true. This behaviour is wrong, in CNM URL server should be visible always.
- [ ] When I realize login changing url server, then I can not select org unit because always request login again. I can not complete login process (login + select org unit)

### PR DESCRIPTION
**Pull request by idelcano**
### :pushpin: References
* **Issue:** close #2278 
* **Related pull-requests: https://github.com/EyeSeeTea/pictureapp/pull/2273 ** 

### :tophat: What is the goal?

 Fix the problems::
-[x] ServerURL is showed only when developer options preference is true. This behaviour is wrong, in CNM URL server should be visible always.
-[x] When I realize login changing url server, then I can not select org unit because always request login again. I can not complete login process (login + select org unit)

### :memo: How is it being implemented?

I remove strange code who remove the server setting.

And i removed a old variable.

### :boom: How can it be tested?

- [ ] **Use case 1:** Login with cnm and with ereferals, go to settings and change url.

### :floppy_disk: Requires DB migration?

- [x] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### :art: UI changes?

- [x] Nope, the UI remains as beautiful as it was before!
- [ ] Yeap, here you have some screenshots-

### CODE REVIEW

**Review by xurxodev — COMMENTED** [review]
@idelcano this cnm branch has a connect branch as base, It's correct?

**Comment by idelcano** [comment]
@xurxodev  no, this Branch starts from https://github.com/EyeSeeTea/pictureapp/issues/2250 as is required by the issue https://github.com/EyeSeeTea/pictureapp/issues/2278

This bug is introduced in 2250 and doesn't exist in other Branch.

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano please wait until that issue #2250 is merged because is required by issue and then review this issue changing base to development

**Review by xurxodev — APPROVED** [review]
thanks @idelcano

**Pull request merged**
