### PR TITLE
Showing error message when unable to open a unsupported file

### LINKED ISSUE #1822: Avoid opening unsupported extensions
unsupported formats like PDF shouldn't try to open. Add a minimum validation before launching the intent based on the extension of the file

### PR DESCRIPTION
**Pull request by Amejia481**
close #1822

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@Amejia481 there's a new requirement here. Apparently, the apps crashing on the grid view when trying to preview anything that's not an image or a video. Could you please add a "No preview available" free image for these cases? Thanks!

**Comment by Amejia481** [comment]
Sure, I'll do it!

**Comment by Amejia481** [comment]
Done!
screenshot_1518621626

**Review by ifoche — APPROVED** [review]
thanks @Amejia481. I've noticed that anyone who may have a pdf previously downloaded could still have a crash because the media was downloaded and not identified in the DB as unknown. However I'm not asking for any migration here because I think there's no pdf currently on the field, so I will simply prevent the client. Thank you for this code.

**Pull request merged**
