### PR TITLE
Migration 14: Dropping and recreating DB Schema

### LINKED ISSUE #1903: Add global migration

### PR DESCRIPTION
**Pull request by Amejia481**
close #1903

### CODE REVIEW

**Comment by Amejia481** [comment]
Instructions:

1. Change `AppDatabase.VERSION` to a  lower version than **14 (13,11 .. etc)**
2. Install the app
3. Change `AppDatabase.VERSION` to  **14**
4. Run the app on debugging

 **/pictureapp/app/src/cnm/java/org/eyeseetea/malariacare/data/database/migrations/Migration14DropAllTables.java**

The method below should run without errors.
```java
    @Override
    public void migrate(DatabaseWrapper database) {

        dropAndRecreateDBSchema(database);

    }
```

**Review by ifoche — CHANGES_REQUESTED** [review]
@Amejia481 it doesn't seems to be working. The idea of this global migration is to allow people that had the previous version to install the new one on top of that one. So to replicate that situation you have to...

0) Delete any version of the app you could have installed in your device
1) Move your pictureapp branch to commit f35fc143b
2) Move your EyeSeeTea-sdk branch to development
3) Move your sdk branch to 2.25_EyeSeeTea
4) Manually remove the _bb part in the applicationId for cnm variant
5) Generate an apk and install the app. You'll have the previous version now as users have it
6) Move your pictureapp branch to feature-add_global_migration
7) Move your EyeSeeTea-sdk branch to feature-update_buildtools_version
8) Move your sdk branch to 2.25_EyeSeeTea_update_support-version
9) Generate an apk and install the app again. Now your migration will apply, and as a result, the app should be completely functional but with it's crashing for me.

**Comment by Amejia481** [comment]
Thanks @ifoche, I on it!

**Comment by Amejia481** [comment]
Hi @ifoche!
I followed the step above, but I couldn't replicate the crash.
Could please you provide me the log crash?

**Review by ifoche — APPROVED** [review]
thanks @Amejia481

**Pull request merged**
