### PR TITLE
Add new questions and options to csvs

### LINKED ISSUE #1531: New config file to split into csv

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Ask @ifoche for ZW program uid
Close #1531

### CODE REVIEW

**Comment by ifoche** [comment]
@manuelplazaspalacio, @xurxodev I added ZW program UID directly into the Programs.csv file

**Comment by manuelplazaspalacio** [comment]
Solved bug  @xurxodev

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio an exception ocurred when I select VMMC for user 8004 with Zimbawe.
[error_zw](https://user-images.githubusercontent.com/5593590/31235213-2f45f46c-a9f1-11e7-8846-77ee10737bba.png)

Exception:
10-05 17:14:04.706 6323-6756/org.eyeseetea.surveillance_ref_bb D/OkHttp: {"versionWS":"v 1.04","response":{"msg":"One or more actions failed","returnCode":400,"orgUnit":{"name":"eRef IPC 8004 [TESTOU]","id":"ZUF1vSkQaB0"}},"version":"1.0","actions":[{"timeOnQueue":"","response":{"msg":"-- ipc_issueEntry_msg_creatingClient ... -- ipc_issueEntry_msg_cientCreatedWithId 'Yy9eAesAVL1'.-- ipc_issueEntry_msg_clientCUICis 'TGTGMGTTG17'.-- ipc_issueEntry_msg_enrollingClient ... -- ipc_issueEntry_msg_enrolledClientInProgram 'eReferrals - Clients'-- ipc_issueEntry_msg_creatingEventForTheClient ...","data":{"clientId":"Yy9eAesAVL1","CUIC":"TGTGMGTTG17"}},"actionId":"b3TKhk1RZhN","type":"issueReferral","message":"Failed to issue a referral. - Error on issuing: Error on create client event, clientID: Yy9eAesAVL1, orgUnit: ZUF1vSkQaB0","status":"failed"}]}
10-05 17:14:04.706 6323-6756/org.eyeseetea.surveillance_ref_bb D/OkHttp: <-- END HTTP (780-byte body)
10-05 17:14:04.712 6323-6756/org.eyeseetea.surveillance_ref_bb I/System.out: org.eyeseetea.malariacare.domain.exception.push.PushValueException message Survey with id: b3TKhk1RZhN has conflicts: Failed to issue a referral. - Error on issuing: Error on create client event, clientID: Yy9eAesAVL1, orgUnit: ZUF1vSkQaB0. Detail message: -- ipc_issueEntry_msg_creatingClient ... -- ipc_issueEntry_msg_cientCreatedWithId 'Yy9eAesAVL1'.-- ipc_issueEntry_msg_clientCUICis 'TGTGMGTTG17'.-- ipc_issueEntry_msg_enrollingClient ... -- ipc_issueEntry_msg_enrolledClientInProgram 'eReferrals - Clients'-- ipc_issueEntry_msg_creatingEventForTheClient ...

**Review by xurxodev — APPROVED** [review]
@manuelplazaspalacio I approve this PR because the last conflict seems a server problem (ws)

**Pull request merged**
