### PR TITLE
Solved bugs in eReferrals tests.

### LINKED ISSUE #2251: Fix failed unit and instrumentation test in eReferrals

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
### :pushpin: References
* **Issue:** close #2251 
* **Related pull-requests:** 

### :tophat: What is the goal?

Solve de bugs in eReferrlas tests.

### :memo: How is it being implemented?

Solving int the different failing tests.

### :boom: How can it be tested?

- [ ] **Use case 1:** Put the eReferrals staging branch and run the tests. 

### :floppy_disk: Requires DB migration?

- [x] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### :art: UI changes?

- [x] Nope, the UI remains as beautiful as it was before!
- [ ] Yeap, here you have some screenshots-

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio there are failing test.
Instrumentation test is ok but unit test is not ok.
Please merge with branch on issue https://github.com/EyeSeeTea/pictureapp/pull/2248 where dhis sdk is removed from ereferrals and review again the tests

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio First I have merged with last PR https://github.com/EyeSeeTea/pictureapp/pull/2273 and I have resolved compile errors then, when I execute the test there failed one again, please can you review it? thanks

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio I'm still having tests that fail, please review it

**Review by xurxodev — APPROVED** [review]
thanks @manuelplazaspalacio .
@ifoche I have approved this PR but it can not be merged into development yet because it was created from the feature-remove_dhis2_server branch that is not merged.
I have reviewed it changing the base branch

**Review by ifoche — APPROVED** [review]
@xurxodev @manuelplazaspalacio honestly I don't understand why this branch needs to contain the libraries upgrade. The 3 PRs from Manu have that base, and it's quite difficult to actually see the changes that the branch tries to merge. As it has already been reviewed by Jorge, I will merge it and proceed with the last 2 PRs likewise, to better assess later. But in my case tests are not working.

**Pull request merged**
