### PR TITLE
Fixing different bottom line margin for dropdown questions

### LINKED ISSUE #1811: Bottom line for some questions show a different margin
Please have a look [here](https://camo.githubusercontent.com/a760ab0211690d7a68de19f02994ae4e49b0824d/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f62756464796275696c642d666565646261636b2f3539323434616636323131626634303030316632326634342f3561366238373532373538393635303030316339626463382f62333534336530372d366562312d346563642d383166622d6534383964613238303165362e6a7067)

### PR DESCRIPTION
**Pull request by Amejia481**
close #1811

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@Amejia481 as expected, margins are slightly different than the rest of rows. Could you please change it to match what's done for the rest? (if you do it today, you can use 8001 user in clone server for testing purposes, I've just configured a yes only question there)

**Comment by Amejia481** [comment]
Sure!

**Review by ifoche — CHANGES_REQUESTED** [review]
@Amejia481 mandatory asterisk looks like having a different alignment. Can you have a look to this? Thanks!

**Review by ifoche — APPROVED** [review]
thanks @Amejia481

**Pull request merged**
